[patch.'https://github.com/oscomp/arceos.git']
axfeat = { path = "arceos/api/axfeat" }
axconfig = { path = "arceos/modules/axconfig" }
axfs = { path = "arceos/modules/axfs" }
axhal = { path = "arceos/modules/axhal" }
axlog = { path = "arceos/modules/axlog" }
axmm = { path = "arceos/modules/axmm" }
axnet = { path = "arceos/modules/axnet" }
axns = { path = "arceos/modules/axns" }
axruntime = { path = "arceos/modules/axruntime" }
axsync = { path = "arceos/modules/axsync" }
axtask = { path = "arceos/modules/axtask" }

[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/Azure-stars/lwext4_rust.git"]
git = "https://github.com/Azure-stars/lwext4_rust.git"
replace-with = "vendored-sources"

[source."git+https://github.com/Mivik/page_table_multiarch.git?rev=19ededd"]
git = "https://github.com/Mivik/page_table_multiarch.git"
rev = "19ededd"
replace-with = "vendored-sources"

[source."git+https://github.com/Starry-OS/axprocess.git"]
git = "https://github.com/Starry-OS/axprocess.git"
replace-with = "vendored-sources"

[source."git+https://github.com/Starry-OS/axsignal.git?rev=b5b6089"]
git = "https://github.com/Starry-OS/axsignal.git"
rev = "b5b6089"
replace-with = "vendored-sources"

[source."git+https://github.com/Starry-OS/weak-map.git"]
git = "https://github.com/Starry-OS/weak-map.git"
replace-with = "vendored-sources"

[source."git+https://github.com/arceos-org/allocator.git?tag=v0.1.1"]
git = "https://github.com/arceos-org/allocator.git"
tag = "v0.1.1"
replace-with = "vendored-sources"

[source."git+https://github.com/arceos-org/axdriver_crates.git?tag=v0.1.2"]
git = "https://github.com/arceos-org/axdriver_crates.git"
tag = "v0.1.2"
replace-with = "vendored-sources"

[source."git+https://github.com/arceos-org/linked_list.git?tag=v0.1.0"]
git = "https://github.com/arceos-org/linked_list.git"
tag = "v0.1.0"
replace-with = "vendored-sources"

[source."git+https://github.com/arceos-org/scheduler.git?tag=v0.1.0"]
git = "https://github.com/arceos-org/scheduler.git"
tag = "v0.1.0"
replace-with = "vendored-sources"

[source."git+https://github.com/jasonwhite/syscalls.git?rev=92624de"]
git = "https://github.com/jasonwhite/syscalls.git"
rev = "92624de"
replace-with = "vendored-sources"

[source."git+https://github.com/oscomp/arceos.git"]
git = "https://github.com/oscomp/arceos.git"
replace-with = "vendored-sources"

[source."git+https://github.com/rafalh/rust-fatfs?rev=85f06e0"]
git = "https://github.com/rafalh/rust-fatfs"
rev = "85f06e0"
replace-with = "vendored-sources"

[source."git+https://github.com/rcore-os/smoltcp.git?rev=2ade274"]
git = "https://github.com/rcore-os/smoltcp.git"
rev = "2ade274"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor/"